name: CD

on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: mypython

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/mypython .

      - name: Push Docker image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/mypython

      - name: Update values.yaml
        run: |
          cd check-argocd
          sed -i 's/\(APP_VERSION: \)\([0-9]\+\)/echo "\1$((\2+1))"/ge' values.yaml 
          git config --global user.name 'Bui-Tuan'
          git config --global user.email 'tuanbui13072000@gmail.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
